[package]
name = "habitat_butterfly"
version = "0.1.0"
authors = ["Adam Jacob <adam@chef.io>"]
build = "build.rs"
workspace = "../../"

[[bin]]
name = "butterfly"
doc = false

[dev-dependencies.habitat_butterfly_test]
path = "../butterfly-test"

[build-dependencies]
pkg-config = "0.3"

[dependencies]
byteorder = "1.0.0"
env_logger = "*"
log = "*"
lazy_static = "*"
protobuf = "*"
rand = "*"
serde = "*"
serde_derive = "*"
time = "*"
threadpool = "*"
toml = { version = "*", features = ["serde"], default-features = false, git = "https://github.com/alexcrichton/toml-rs" , rev = "d39c3f7b3ec95cb3cc1e579d7d747206c66aab74"}

[dependencies.uuid]
version = "*"
features = ["v4"]

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[dependencies.habitat_core]
path = "../core"

[features]
functional = []
protocols = []
